wandb_version: 1

setup:
  desc: null
  value: task IL
learning_rate:
  desc: null
  value: 0.1
architecture:
  desc: null
  value: NetTaskIL
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682594103.441947
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.0
      8:
      - 5
