# sbatch schedule_0.sh
sbatch schedule_1.sh
sbatch schedule_2.sh
sbatch schedule_3.sh
sbatch schedule_4.sh
sbatch schedule_5.sh
sbatch schedule_6.sh
sbatch schedule_7.sh
sbatch schedule_8.sh
sbatch schedule_9.sh
sbatch schedule_10.sh
sbatch schedule_11.sh
sbatch schedule_12.sh
sbatch schedule_13.sh
sbatch schedule_14.sh
sbatch schedule_15.sh
sbatch schedule_16.sh
sbatch schedule_17.sh
sbatch schedule_18.sh
sbatch schedule_19.sh
sbatch schedule_20.sh
